### ISSUE TITLE
CUDA Out of Memory Error when Running SFT

### ISSUE THREAD

**Issue by smanzinger** [nvidia-cosmos/cosmos-reason1#40]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Question
- [ ] Documentation
- [ ] Security
- [ ] Other

## Description

I tried to run SFT for Cosmos-Reason1 according to the instructions in the GitHub repository. With the available recipes, I get a CUDA out-of-memory error. I am working with 8xH100-80GB. 

Reducing train_batch_per_replica to 4 resolves the error.

## Steps to Reproduce (for bugs)

1. Follow the instructions provided in the Cosmos-Reason1 GitHub repository to install system dependencies and packages, see cosmos-reason1/examples/cosmos_reason1_sft_dataset/README.md.
2. Start SFT as described under Training Scripts - Supervised Fine-Tuning (SFT) in the cosmos-reason1/examples/cosmos_reason1_sft_dataset/README.md.
3. The CUDA out-of-memory occurs for the following SFT training recipes: cosmos-reason1-7b-fsdp2-sft.toml and cosmos-reason1-7b-fsdp4-sft.toml. (No test were conducted with cosmos-reason1-7b-fsdp8-sft.toml)

## Expected Behavior

The training should execute successfully using the provided recipes without running into memory issues, given the available compute resources.

## Actual Behavior

A CUDA out of memory error occurs during execution. Reducing train_batch_per_replica to 4 resolves the error.

## Environment

- Model Name/Version: Cosmos-Reason1
- Framework (e.g., Docker, Conda): Conda
- Python Version: Python 3.12.11
- OS/Platform: Ubuntu 22.04.4 LTS
- GPU/CPU: 8 x NVIDIA H100 NVL 
- Additional Dependencies:  Driver Version: 570.124.06, CUDA Version: 12.8 

## Additional Context

[log.txt](https://github.com/user-attachments/files/21583810/log.txt)

**Comment by smanzinger** [comment]
> [@smanzinger](https://github.com/smanzinger) We just updated the tutorial, and tested that it works. I encountered the same issue with the previous version. Can you please retry?

Tested the changes and SFT is working now 👍. Thank you!
